/**
 * @file romemul.pio.h
 * @brief PIO program for 68000 bus monitor (generated from romemul.pio)
 *
 * This is a placeholder. In a real build, this would be generated by
 * pioasm from romemul.pio. For now, we include inline assembly.
 */

#ifndef ROMEMUL_PIO_H
#define ROMEMUL_PIO_H

#include "hardware/pio.h"

// Placeholder: In real build, pioasm generates this from romemul.pio
// For now, the PIO program is inline in romemul.c

#endif /* ROMEMUL_PIO_H */
